//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGH
{
    using System;
    using System.Collections.Generic;
    
    public partial class Course
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Course()
        {
            this.Student_Course = new HashSet<Student_Course>();
        }
    
        public int CourseID { get; set; }
        public string Course_Name { get; set; }
        public string Course_Code { get; set; }
        public string Course_Description { get; set; }
        public int Course_Credit { get; set; }
        public int Course_Instructor_ID { get; set; }
        public int Course_Assistant_ID { get; set; }
        public bool Is_Course_Deleted { get; set; }
    
        public virtual Assistant Assistant { get; set; }
        public virtual Instructor Instructor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Student_Course> Student_Course { get; set; }
    }
}
